services:
  api:
    image: ghcr.io/saleor/saleor:3.22
    ports:
      - 8080:8000
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    stdin_open: true
    tty: true
    depends_on:
      - db
      - cache
      - jaeger
    volumes:
      - saleor-media:/app/media
    env_file:
      - common.env
      - backend.env
    environment:
      - DASHBOARD_URL=http://localhost:9002/
      - ALLOWED_HOSTS=localhost,127.0.0.1,api

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    ports:
      - 9002:80
    restart: unless-stopped
    environment:
      - API_URL=http://localhost:8080/graphql/
      - APPS_MARKETPLACE_API_URL=https://apps.saleor.io/api/v2/saleor-apps
      - EXTENSIONS_API_URL=https://apps.saleor.io/api/v1/extensions

  db:
    image: library/postgres:15-alpine
    ports:
      - 5434:5432
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql/data
      - ./replica_user.sql:/docker-entrypoint-initdb.d/replica_user.sql:ro,z
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  cache:
    image: valkey/valkey:8.1-alpine
    ports:
      - 6381:6379
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-cache:/data

  worker:
    image: ghcr.io/saleor/saleor:3.22
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file:
      - common.env
      - backend.env
    depends_on:
      - cache
      - mailpit
    volumes:
      - saleor-media:/app/media

  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "16687:16686"
      - "4319:4317"
      - "4320:4318"
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - type: tmpfs
        target: /tmp

  mailpit:
    image: axllent/mailpit
    ports:
      - 1026:1025 # smtp server
      - 8026:8025 # web ui
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-db:
    driver: local
  saleor-cache:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
